### ISSUE TITLE
Wrong directory for PEM file having a key? 

### ISSUE THREAD

**Issue by egberts** [egberts/tls-ca-manage#9]
I think I have a bug where I misplaced the `.key`-type file into the wrong `/etc/ssl/certs/` directory whereas it should have been stored into the more secured `/etc/ssl/private` subdirectory for centralized traditional mode.
"
The bug isn't exactly an execution bug because OpenSSL command still can references the file at anywhere via BASH aliasing through variable names, but more like the security operational theater bug of enforcement and protection of key files through file permission.

https://github.com/egberts/tls-ca-manage/blame/8bce1dbc48bfee83eef7b98a7afba61656cefad5/tls-cert-manage.sh#L408
```diff
-        CERT_KEY_DIR="$SSL_DIR/$CERTS_DNAME"
+       # WHY ARE PRIVATE CERT KEYS GOING INTO /etc/ssl/certs???? in Centralized?
+        #####CERT_KEY_DIR="$SSL_DIR/$CERTS_DNAME"   # NIX THIS!
+        CERT_KEY_DIR="$SSL_DIR/$PRIVATE_DNAME"
```
@joaocc, what do you think?  Just for traditional centralized mode, that the `.key` file should end up into the `/etc/ssl/private` subdirectory?

**Comment by joaocc** [comment]
Hi. Thanks for the opportunity, but I don't know much enough about openssl to have an opinion.
I'm just a user-with-a-need and with some bash time on my hands at the time :)
I ended up using the non hierarchical mode due to the issue reported in another ticket, and will prob not have the time to assist in further testing.
Sorry and thanks for the amazing work.

**Comment by egberts** [comment]
fixed in commit 

https://github.com/egberts/tls-ca-manage/commit/7526b809e52f14f8ef634c22d4443edcc058e81f
